name = "RandomFeatureMaps"
uuid = "780baa95-dd42-481b-93db-80fe3d88832c"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "0.2.2"

[deps]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[weakdeps]
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"

[extensions]
GraphNeuralNetworksExt = "GraphNeuralNetworks"

[compat]
BatchedTransformations = "0.5"
Flux = "0.14, 0.15, 0.16"
GraphNeuralNetworks = "0.6, 1.0"
julia = "1.10"

[extras]
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GraphNeuralNetworks"]
