name = "RandomFeatureMaps"
uuid = "780baa95-dd42-481b-93db-80fe3d88832c"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "0.2.0"

[deps]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"

[weakdeps]
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"

[extensions]
GraphNeuralNetworksExt = "GraphNeuralNetworks"

[compat]
BatchedTransformations = "0.5"
Functors = "0.4"
GraphNeuralNetworks = "0.6"
Optimisers = "0.3"
julia = "1.9"

[extras]
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GraphNeuralNetworks"]
